import type { Metadata } from 'next'
import './globals.css'

import inject from '@stylexjs/dev-runtime'

// inject({
//   classNamePrefix: 'x',
//   dev: true,
//   test: false,
// })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
